name: First Workflow
on: workflow_dispatch
jobs:
 first-ob:
  runs-on: ubuntu-latests
  steps:
     - name: Print greeting
     - run: echo "Hello world" 
     - name: Print goodbye
     - run: "echo bye"
   
